### ISSUE TITLE
"Uncaught TypeError: Illegal invocation" when using changes()

### ISSUE THREAD

**Issue by vovayartsev** [mikemintz/rethinkdb-websocket-client#5]
Hi,
I'm not quite sure which component caused this issue, but I suspect it's something websocket-related.

RethinkDB + Websockify is hosted in Tutum with the following Stackfile (mostly docker-compose.yml): 

```
rethinkdb:
  image: anapsix/rethinkdb:latest
  ports:
    - "8080:8080"
    - "28015:28015"
websockify:
  image: siboulet/websockify:latest
  command: '8015 rethinkdb:28015'
  ports:
    - "8015:8015"
```

When running the example below, I get "Uncaught TypeError: Illegal invocation"

```
  var options = {
    host: 'fbae7f61-dockhero.node.tutum.io',       // hostname of the websocket server
    port: 8015,              // port number of the websocket server
    path: '/',               // HTTP path to websocket route
    wsProtocols: ['binary'], // sub-protocols for websocket, required for websockify
    secure: false,           // set true to use secure TLS websockets
    db: 'domaino',              // default database, passed to rethinkdb.connect
    simulatedLatencyMs: 100, // wait 100ms before sending each message (optional)
  };

  RethinkdbWebsocketClient.connect(options).then(function (conn) {
    r.table('domains').get("2ezrJu4iqoo4h2").changes().run(conn, function(err, cursor) {
      cursor.each(console.log);
    });
  });
```

Just to give some context, queries which just fetch data once (like `r.table('domains').run(...)`) work fine. Queries which wait for the changes in a collection would fail when the change actually happens. Queries waiting for the changes in a point (like in the code above) fail immediately.

I'll keep the server mentioned in the code above alive for the next several days so that you could reproduce the issue by running the code snippet above as is.

Tested in Chrome Version 46.0.2490.86 (64-bit) on Mac OS and latest Safari.
Thanks, Vladimir
